# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.10"

agp = "8.12.3"

androidxCore = "1.17.0"
androidxLifecycle = "2.10.0"
androidxActivity = "1.13.0"

composeBom = "2026.06.01"

androidxComposeNav = "2.9.8"
activityKtx = "1.13.0"

ktor = "3.3.3"
kotlinxSerialization = "1.9.0"

kotlinxCoroutines = "1.10.2"
oldMaterialIcons = "1.7.8"

mDNS = "3.6.3"

ksp = "2.2.10-2.0.2"
autoService = "1.1.1"
autoServiceKsp = "1.2.0"

camerax = "1.6.1"

mlkit = "17.3.0"

[libraries]
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxLifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidxActivity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxComposeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }

androidxComposeUi = { module = "androidx.compose.ui:ui" }
androidxComposeGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidxComposeMaterial3 = { module = "androidx.compose.material3:material3" }

androidxComposeNav = { module = "androidx.navigation:navigation-compose", version.ref = "androidxComposeNav" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

ktorCore = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktorCio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
ktorWebsockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }
ktorContentNegotation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorClientWebsockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktorCors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientCio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }

kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

ktorSerialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinxCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

mDnsCore = { group = "org.jmdns", name = "jmdns", version.ref = "mDNS" }
materialIconsOld = { group="androidx.compose.material" , name ="material-icons-core", version.ref = "oldMaterialIcons"}
composeMaterial = { module = "androidx.compose.material:material" }

autoServiceAnnotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "autoService" }
autoServiceKsp = { group = "dev.zacsweers.autoservice", name = "auto-service-ksp", version.ref = "autoServiceKsp" }

androidxCameraCore = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
androidxCamera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
androidxCameraLifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidxCameraView = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }

mlkit = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }